// CAL-GETC mapping: maps normalized Subject_Course to one or more CAL-GETC areas and divisions

window.CAL_GETC_MAPPING = [
  // Area 1: English Communication
  { code: "ENGL C1000", areas: ["CAL-GETC Area 1"], divisions: ["CAL-GETC Area 1 - Fine Arts & English"] },
  { code: "ENGL C1001", areas: ["CAL-GETC Area 1"], divisions: ["CAL-GETC Area 1 - Fine Arts & English"] },
  { code: "PHIL 025", areas: ["CAL-GETC Area 1"], divisions: ["CAL-GETC Area 1 - Social Science & CFS"] },
  { code: "COMM C1000", areas: ["CAL-GETC Area 1"], divisions: ["CAL-GETC Area 1 - Lang & Comm."] },

  // Area 2: Mathematical Concepts and Quantitative Reasoning
  { code: "BUS 020", areas: ["CAL-GETC Area 2"], divisions: ["CAL-GETC Area 2 - Social Science & CFS"] },
  { code: "MATH 035", areas: ["CAL-GETC Area 2"], divisions: ["CAL-GETC Area 2 - Math, SCI & ENG"] },
  { code: "MATH 044", areas: ["CAL-GETC Area 2"], divisions: ["CAL-GETC Area 2 - Math, SCI & ENG"] },
  { code: "MATH 054", areas: ["CAL-GETC Area 2"], divisions: ["CAL-GETC Area 2 - Math, SCI & ENG"] },
  { code: "MATH 065", areas: ["CAL-GETC Area 2"], divisions: ["CAL-GETC Area 2 - Math, SCI & ENG"] },
  { code: "MATH 066", areas: ["CAL-GETC Area 2"], divisions: ["CAL-GETC Area 2 - Math, SCI & ENG"] },
  { code: "MATH 067", areas: ["CAL-GETC Area 2"], divisions: ["CAL-GETC Area 2 - Math, SCI & ENG"] },
  { code: "MATH 070", areas: ["CAL-GETC Area 2"], divisions: ["CAL-GETC Area 2 - Math, SCI & ENG"] },
  { code: "MATH 080", areas: ["CAL-GETC Area 2"], divisions: ["CAL-GETC Area 2 - Math, SCI & ENG"] },
  { code: "MATH 081", areas: ["CAL-GETC Area 2"], divisions: ["CAL-GETC Area 2 - Math, SCI & ENG"] },
  { code: "SSCI 025", areas: ["CAL-GETC Area 2"], divisions: ["CAL-GETC Area 2 - Social Science & CFS"] },
  { code: "STAT C1000", areas: ["CAL-GETC Area 2"], divisions: ["CAL-GETC Area 2 - Math, SCI & ENG"] },

  // Area 3: Arts and Humanities
  // 3A: Arts
  { code: "ARCH 070", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Career Tech"] },
  { code: "ARCH 071", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Career Tech"] },
  { code: "ART 001", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Fine Arts & English"] },
  { code: "ART 002", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Fine Arts & English"] },
  { code: "ART 003", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Fine Arts & English"] },
  { code: "ART 004", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Fine Arts & English"] },
  { code: "ART 005", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Fine Arts & English"] },
  { code: "ART 081", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Fine Arts & English"] },
  { code: "CINA 031", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Fine Arts & English"] },
  { code: "CINA 032", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Fine Arts & English"] },
  { code: "DRAM 001", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Fine Arts & English"] },
  { code: "DRAM 006", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Fine Arts & English"] },
  { code: "MUS 004", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Fine Arts & English"] },
  { code: "MUS 005", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Fine Arts & English"] },
  { code: "MUS 006", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Fine Arts & English"] },
  { code: "MUS 007", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Fine Arts & English"] },
  { code: "MUS 010", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Fine Arts & English"] },
  { code: "MUS 011", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Fine Arts & English"] },
  { code: "MUS 013", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Fine Arts & English"] },
  { code: "MUS 014", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Fine Arts & English"] },
  // 3B: Humanities
  { code: "ASL 003", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Lang & Comm."] },
  { code: "ASL 004", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Lang & Comm."] },
  { code: "ASL 005", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Lang & Comm."] },
  { code: "ENGL 004", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Fine Arts & English"] },
  { code: "ENGL 010", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Fine Arts & English"] },
  { code: "ENGL 015", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Fine Arts & English"] },
  { code: "ENGL 016", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Fine Arts & English"] },
  { code: "ENGL 018", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Fine Arts & English"] },
  { code: "ENGL 019", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Fine Arts & English"] },
  { code: "ENGL 030", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Fine Arts & English"] },
  { code: "ENGL 031", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Fine Arts & English"] },
  { code: "ENGL 044", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Fine Arts & English"] },
  { code: "ENGL 045", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Fine Arts & English"] },
  { code: "ENGL 046", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Fine Arts & English"] },
  { code: "ETHN 001", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Social Science & CFS"] },
  { code: "ETHN 002", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Social Science & CFS"] },
  { code: "ETHN 003", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Social Science & CFS"] },
  { code: "ETHN 004", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Social Science & CFS"] },
  { code: "ETHN 010", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Social Science & CFS"] },
  { code: "HIST 004", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Social Science & CFS"] },
  { code: "HIST 005", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Social Science & CFS"] },
  { code: "HIST 017", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Social Science & CFS"] },
  { code: "HIST 018", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Social Science & CFS"] },
  { code: "HIST 023", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Social Science & CFS"] },
  { code: "HIST 025", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Social Science & CFS"] },
  { code: "PHIL 001", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Social Science & CFS"] },
  { code: "PHIL 005", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Social Science & CFS"] },
  { code: "PHIL 012", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Social Science & CFS"] },
  { code: "SPAN 003", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Lang & Comm."] },
  { code: "SPAN 004", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Lang & Comm."] },
  { code: "SPAN 012", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Lang & Comm."] },
  { code: "SPAN 023", areas: ["CAL-GETC Area 3"], divisions: ["CAL-GETC Area 3 - Lang & Comm."] },

  // Area 4: Social and Behavioral Sciences
  { code: "AG 001", areas: ["CAL-GETC Area 4"], divisions: ["CAL-GETC Area 4 - Career Tech"] },
  { code: "AGMT 001", areas: ["CAL-GETC Area 4"], divisions: ["CAL-GETC Area 4 - Career Tech"] },
  { code: "AJ 045", areas: ["CAL-GETC Area 4"], divisions: ["CAL-GETC Area 4 - Social Science & CFS"] },
  { code: "ANTH 010", areas: ["CAL-GETC Area 4"], divisions: ["CAL-GETC Area 4 - Social Science & CFS"] },
  { code: "ANTH 012", areas: ["CAL-GETC Area 4"], divisions: ["CAL-GETC Area 4 - Social Science & CFS"] },
  { code: "ANTH 013", areas: ["CAL-GETC Area 4"], divisions: ["CAL-GETC Area 4 - Social Science & CFS"] },
  { code: "CHLD 039", areas: ["CAL-GETC Area 4"], divisions: ["CAL-GETC Area 4 - Social Science & CFS"] },
  { code: "CHLD 042", areas: ["CAL-GETC Area 4"], divisions: ["CAL-GETC Area 4 - Social Science & CFS"] },
  { code: "COMM 002", areas: ["CAL-GETC Area 4"], divisions: ["CAL-GETC Area 4 - Lang & Comm."] },
  { code: "COMM 009", areas: ["CAL-GETC Area 4"], divisions: ["CAL-GETC Area 4 - Lang & Comm."] },
  { code: "ECON 025", areas: ["CAL-GETC Area 4"], divisions: ["CAL-GETC Area 4 - Social Science & CFS"] },
  { code: "ECON 040", areas: ["CAL-GETC Area 4"], divisions: ["CAL-GETC Area 4 - Social Science & CFS"] },
  { code: "ECON 050", areas: ["CAL-GETC Area 4"], divisions: ["CAL-GETC Area 4 - Social Science & CFS"] },
  { code: "ETHN 001", areas: ["CAL-GETC Area 4"], divisions: ["CAL-GETC Area 4 - Social Science & CFS"] },
  { code: "ETHN 002", areas: ["CAL-GETC Area 4"], divisions: ["CAL-GETC Area 4 - Social Science & CFS"] },
  { code: "ETHN 003", areas: ["CAL-GETC Area 4"], divisions: ["CAL-GETC Area 4 - Social Science & CFS"] },
  { code: "ETHN 004", areas: ["CAL-GETC Area 4"], divisions: ["CAL-GETC Area 4 - Social Science & CFS"] },
  { code: "ETHN 010", areas: ["CAL-GETC Area 4"], divisions: ["CAL-GETC Area 4 - Social Science & CFS"] },
  { code: "GEOG 002", areas: ["CAL-GETC Area 4"], divisions: ["CAL-GETC Area 4 - Math, SCI & ENG"] },
  { code: "HIST 004", areas: ["CAL-GETC Area 4"], divisions: ["CAL-GETC Area 4 - Social Science & CFS"] },
  { code: "HIST 005", areas: ["CAL-GETC Area 4"], divisions: ["CAL-GETC Area 4 - Social Science & CFS"] },
  { code: "HIST 017", areas: ["CAL-GETC Area 4"], divisions: ["CAL-GETC Area 4 - Social Science & CFS"] },
  { code: "HIST 018", areas: ["CAL-GETC Area 4"], divisions: ["CAL-GETC Area 4 - Social Science & CFS"] },
  { code: "HIST 023", areas: ["CAL-GETC Area 4"], divisions: ["CAL-GETC Area 4 - Social Science & CFS"] },
  { code: "HIST 025", areas: ["CAL-GETC Area 4"], divisions: ["CAL-GETC Area 4 - Social Science & CFS"] },
  { code: "JOUR 007", areas: ["CAL-GETC Area 4"], divisions: ["CAL-GETC Area 4 - Lang & Comm."] },
  { code: "JOUR 020", areas: ["CAL-GETC Area 4"], divisions: ["CAL-GETC Area 4 - Lang & Comm."] },
  { code: "NUTR 020", areas: ["CAL-GETC Area 4"], divisions: ["CAL-GETC Area 4 - Physical Education"] },
  { code: "PHSC 002", areas: ["CAL-GETC Area 4"], divisions: ["CAL-GETC Area 4 - Physical Education"] },
  { code: "POLS C1000", areas: ["CAL-GETC Area 4"], divisions: ["CAL-GETC Area 4 - Social Science & CFS"] },
  { code: "POLS 006", areas: ["CAL-GETC Area 4"], divisions: ["CAL-GETC Area 4 - Social Science & CFS"] },
  { code: "POLS 008", areas: ["CAL-GETC Area 4"], divisions: ["CAL-GETC Area 4 - Social Science & CFS"] },
  { code: "POLS 011", areas: ["CAL-GETC Area 4"], divisions: ["CAL-GETC Area 4 - Social Science & CFS"] },
  { code: "POLS 012", areas: ["CAL-GETC Area 4"], divisions: ["CAL-GETC Area 4 - Social Science & CFS"] },
  { code: "PSYC C1000", areas: ["CAL-GETC Area 4"], divisions: ["CAL-GETC Area 4 - Social Science & CFS"] },
  { code: "PSYC 005", areas: ["CAL-GETC Area 4"], divisions: ["CAL-GETC Area 4 - Social Science & CFS"] },
  { code: "PSYC 010", areas: ["CAL-GETC Area 4"], divisions: ["CAL-GETC Area 4 - Social Science & CFS"] },
  { code: "PSYC 034", areas: ["CAL-GETC Area 4"], divisions: ["CAL-GETC Area 4 - Social Science & CFS"] },
  { code: "PSYC 080", areas: ["CAL-GETC Area 4"], divisions: ["CAL-GETC Area 4 - Social Science & CFS"] },
  { code: "SOC 001", areas: ["CAL-GETC Area 4"], divisions: ["CAL-GETC Area 4 - Social Science & CFS"] },
  { code: "SOC 002", areas: ["CAL-GETC Area 4"], divisions: ["CAL-GETC Area 4 - Social Science & CFS"] },
  { code: "SOC 010", areas: ["CAL-GETC Area 4"], divisions: ["CAL-GETC Area 4 - Social Science & CFS"] },
  { code: "SOC 026", areas: ["CAL-GETC Area 4"], divisions: ["CAL-GETC Area 4 - Social Science & CFS"] },
  { code: "SOC 043", areas: ["CAL-GETC Area 4"], divisions: ["CAL-GETC Area 4 - Social Science & CFS"] },
  { code: "SSCI 050", areas: ["CAL-GETC Area 4"], divisions: ["CAL-GETC Area 4 - Social Science & CFS"] },

  // Area 5: Physical and Biological Sciences
  // 5A: Physical Science
  { code: "AG 004", areas: ["CAL-GETC Area 5"], divisions: ["CAL-GETC Area 5 - Career Tech"] },
  { code: "ASTR 010", areas: ["CAL-GETC Area 5"], divisions: ["CAL-GETC Area 5 - Math, SCI & ENG"] },
  { code: "CHEM 001", areas: ["CAL-GETC Area 5"], divisions: ["CAL-GETC Area 5 - Math, SCI & ENG"] },
  { code: "CHEM 002", areas: ["CAL-GETC Area 5"], divisions: ["CAL-GETC Area 5 - Math, SCI & ENG"] },
  { code: "CHEM 010", areas: ["CAL-GETC Area 5"], divisions: ["CAL-GETC Area 5 - Math, SCI & ENG"] },
  { code: "CHEM 012", areas: ["CAL-GETC Area 5"], divisions: ["CAL-GETC Area 5 - Math, SCI & ENG"] },
  { code: "CHEM 013", areas: ["CAL-GETC Area 5"], divisions: ["CAL-GETC Area 5 - Math, SCI & ENG"] },
  { code: "CHEM 020", areas: ["CAL-GETC Area 5"], divisions: ["CAL-GETC Area 5 - Math, SCI & ENG"] },
  { code: "CHEM 021", areas: ["CAL-GETC Area 5"], divisions: ["CAL-GETC Area 5 - Math, SCI & ENG"] },
  { code: "GEOG 001", areas: ["CAL-GETC Area 5"], divisions: ["CAL-GETC Area 5 - Math, SCI & ENG"] },
  { code: "GEOG 005", areas: ["CAL-GETC Area 5"], divisions: ["CAL-GETC Area 5 - Math, SCI & ENG"] },
  { code: "GEOL 001", areas: ["CAL-GETC Area 5"], divisions: ["CAL-GETC Area 5 - Math, SCI & ENG"] },
  { code: "GEOL 005", areas: ["CAL-GETC Area 5"], divisions: ["CAL-GETC Area 5 - Math, SCI & ENG"] },
  { code: "GEOL 012", areas: ["CAL-GETC Area 5"], divisions: ["CAL-GETC Area 5 - Math, SCI & ENG"] },
  { code: "PHYS 020", areas: ["CAL-GETC Area 5"], divisions: ["CAL-GETC Area 5 - Math, SCI & ENG"] },
  { code: "PHYS 021", areas: ["CAL-GETC Area 5"], divisions: ["CAL-GETC Area 5 - Math, SCI & ENG"] },
  { code: "PHYS 055", areas: ["CAL-GETC Area 5"], divisions: ["CAL-GETC Area 5 - Math, SCI & ENG"] },
  { code: "PHYS 056", areas: ["CAL-GETC Area 5"], divisions: ["CAL-GETC Area 5 - Math, SCI & ENG"] },
  { code: "PHYS 057", areas: ["CAL-GETC Area 5"], divisions: ["CAL-GETC Area 5 - Math, SCI & ENG"] },
  { code: "PSCI 020", areas: ["CAL-GETC Area 5"], divisions: ["CAL-GETC Area 5 - Math, SCI & ENG"] },
  // 5B: Biological Science
  { code: "AG 002", areas: ["CAL-GETC Area 5"], divisions: ["CAL-GETC Area 5 - Career Tech"] },
  { code: "ANTH 011", areas: ["CAL-GETC Area 5"], divisions: ["CAL-GETC Area 5 - Social Science & CFS"] },
  { code: "BIOL 001", areas: ["CAL-GETC Area 5"], divisions: ["CAL-GETC Area 5 - Math, SCI & ENG"] },
  { code: "BIOL 002", areas: ["CAL-GETC Area 5"], divisions: ["CAL-GETC Area 5 - Math, SCI & ENG"] },
  { code: "BIOL 020", areas: ["CAL-GETC Area 5"], divisions: ["CAL-GETC Area 5 - Math, SCI & ENG"] },
  { code: "BIOL 021", areas: ["CAL-GETC Area 5"], divisions: ["CAL-GETC Area 5 - Math, SCI & ENG"] },
  { code: "BIOL 022", areas: ["CAL-GETC Area 5"], divisions: ["CAL-GETC Area 5 - Math, SCI & ENG"] },
  { code: "BIOL 025", areas: ["CAL-GETC Area 5"], divisions: ["CAL-GETC Area 5 - Math, SCI & ENG"] },
  { code: "BIOL 030", areas: ["CAL-GETC Area 5"], divisions: ["CAL-GETC Area 5 - Math, SCI & ENG"] },
  { code: "BIOL 031", areas: ["CAL-GETC Area 5"], divisions: ["CAL-GETC Area 5 - Math, SCI & ENG"] },
  { code: "BIOL 040", areas: ["CAL-GETC Area 5"], divisions: ["CAL-GETC Area 5 - Math, SCI & ENG"] },
  { code: "PLSI 001", areas: ["CAL-GETC Area 5"], divisions: ["CAL-GETC Area 5 - Career Tech"] },
  // 5C: Lab
  { code: "GEOG 001L", areas: ["CAL-GETC Area 5"], divisions: ["CAL-GETC Area 5 - Math, SCI & ENG"] },

  // Area 6: Ethnic Studies
  { code: "ETHN 001", areas: ["CAL-GETC Area 6"], divisions: ["CAL-GETC Area 6 - Social Science & CFS"] },
  { code: "ETHN 002", areas: ["CAL-GETC Area 6"], divisions: ["CAL-GETC Area 6 - Social Science & CFS"] },
  { code: "ETHN 003", areas: ["CAL-GETC Area 6"], divisions: ["CAL-GETC Area 6 - Social Science & CFS"] },
  { code: "ETHN 004", areas: ["CAL-GETC Area 6"], divisions: ["CAL-GETC Area 6 - Social Science & CFS"] },
  { code: "ETHN 010", areas: ["CAL-GETC Area 6"], divisions: ["CAL-GETC Area 6 - Social Science & CFS"] }
];

// Helper: normalize code (remove duplicate spaces, upper-case)
window.normalizeCALGETCCode = function(str) {
  return String(str || "")
    .replace(/[\u00A0]/g, " ") // replace non-breaking space
    .replace(/\s+/g, " ")
    .trim()
    .toUpperCase();
};
