const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');

const tracker = require('../js/low-enrollment-tracker.js');
const reports = require('../js/config/reports.js');

test('low enrollment tracker parses the workbook shape and hidden reasons fallback', () => {
  const table = [
    ['Report generated by Argos'],
    ['Course(s)', 'CRN(s)', 'Title', 'Cross List', 'CRN Count', 'Current Enrollment', 'Max Enrollment', 'Wait Count', 'Inst. \nMethod', 'Sched \nType', 'Applied Rule', 'Threshold', 'Start Date', 'Division', 'Campus', 'Faculty', 'Justification', 'Comments to VPs Office'],
    ['COMM C1000', '10003, 10004', 'Public Speaking', 'XL1', 2, 18, 30, 0, 'IP', 'LEC', 'Below 70%', 21, '8/10/2026', 'LANGUAGE', 'COS', 'Smith, A', 'Single section Offering in Visalia', 'keep watching'],
    ['MATH 021', '20001', 'Support Algebra', '', 1, 8, 25, 2, 'IP', 'LEC', 'Below 70%', 18, '8/10/2026', 'MATH', 'TCC', 'Jones, B', '', '']
  ];

  const workspace = tracker.parseWorkbookTable(table, { filename: '202710 FA26 Low Enrolled Watchlist_8-4-26.xlsx' });
  assert.equal(workspace.termCode, '202710');
  assert.equal(workspace.displayTerm, 'FALL 2026');
  assert.equal(workspace.initialSnapshotDate, '2026-08-04');
  assert.equal(workspace.rows.length, 2);
  assert.deepEqual(workspace.rows[0].crns, ['10003', '10004']);
  assert.equal(workspace.rows[0].initialEnrollment, 18);
  assert.equal(workspace.rows[0].threshold, 21);
  assert.equal(workspace.rows[0].status, 'Below Threshold');
  assert.ok(workspace.reasons.includes('Dual Enrollment'));
  assert.equal(tracker.DEFAULT_JUSTIFICATIONS.length, 10);
  assert.ok(workspace.importSummary.rowsImported === 2);

  const reasons = tracker.parseReasonsTable([['Reason'], ['Custom reason'], ['Custom reason']]);
  assert.deepEqual(reasons, ['Custom reason']);
});

test('low enrollment update sums cross-listed member CRNs and reports full/partial/missing matches', () => {
  const workspace = tracker.parseWorkbookTable([
    ['Course(s)', 'CRN(s)', 'Title', 'Current Enrollment', 'Max Enrollment', 'Threshold'],
    ['COMM C1000', '10003 / 10004', 'Public Speaking', 18, 30, 21],
    ['ENGL C1000', '30001 / 30002', 'Writing', 10, 30, 21],
    ['MATH 021', '40001', 'Support Algebra', 5, 30, 21]
  ], { filename: '202710 FA26 Low Enrolled Watchlist_8-4-26.xlsx' });

  const csvRows = [
    { CRN: '10003', ACTUAL_ENROLL: '12', 'SUBJECT/COURSE': 'COMM C1000' },
    { CRN: '10003', ACTUAL_ENROLL: '12', 'SUBJECT/COURSE': 'COMM C1000' },
    { CRN: '10004', ACTUAL_ENROLL: '13', 'SUBJECT/COURSE': 'COMM C1000' },
    { CRN: '30001', ACTUAL_ENROLL: '9', 'SUBJECT/COURSE': 'ENGL C1000' }
  ];
  const parsed = tracker.parseEnrollmentCsvRows(csvRows);
  assert.equal(parsed.size, 3);
  assert.equal(parsed.get('10003').enrollment, 12);

  const result = tracker.applyEnrollmentSnapshot(workspace, parsed, { snapshotDate: '2026-08-11', sourceFilename: 'section-seating.csv' });
  assert.equal(result.fullyMatchedRows, 1);
  assert.equal(result.partiallyMatchedRows, 1);
  assert.equal(result.completelyMissingRows, 1);
  assert.equal(result.individualCrnsMatched, 3);
  assert.equal(result.individualCrnsMissing, 2);
  assert.equal(result.newlyMet, 1);
  assert.equal(result.workspace.rows[0].latestEnrollment, 25);
  assert.equal(result.workspace.rows[0].highestEnrollment, 25);
  assert.equal(result.workspace.rows[0].status, 'Threshold Met');
  assert.equal(result.workspace.rows[1].latestEnrollment, 9);
  assert.equal(result.workspace.rows[1].snapshotMatchStatus['2026-08-11'], 'partial');
  assert.deepEqual(result.workspace.rows[1].snapshotMissingCrns['2026-08-11'], ['30002']);
  assert.equal(result.workspace.rows[2].latestEnrollment, null);
  assert.equal(result.workspace.rows[2].status, 'Missing Update');
  assert.deepEqual(result.snapshot.values[result.workspace.rows[0].id].matchedCrns, ['10003', '10004']);
});

test('low enrollment workbook validation rejects missing threshold values', () => {
  assert.throws(() => tracker.parseWorkbookTable([
    ['Course(s)', 'CRN(s)', 'Title', 'Current Enrollment', 'Max Enrollment'],
    ['COMM C1000', '10003', 'Public Speaking', 18, 30]
  ], { filename: '202710 FA26 Low Enrolled Watchlist_8-4-26.xlsx' }), /threshold/i);

  const workspace = tracker.parseWorkbookTable([
    ['Course(s)', 'CRN(s)', 'Title', 'Current Enrollment', 'Max Enrollment'],
    ['COMM C1000', '10003', 'Public Speaking', 18, 30]
  ], { filename: '202710 FA26 Low Enrolled Watchlist_8-4-26.xlsx', throwOnInvalid: false });
  assert.equal(workspace.importErrors.length, 2);
  assert.match(workspace.importErrors.join(' '), /threshold/i);
});

test('low enrollment snapshot date detects source content before filename fallback', () => {
  assert.equal(tracker.detectSnapshotDateFromRows([{ SNAPSHOT_DATE: '8/12/2026' }]), '2026-08-12');
  assert.equal(tracker.extractSnapshotDateFromFilename('202710 FA26 Low Enrolled Watchlist_8-4-26.xlsx'), '2026-08-04');
});

test('low enrollment start dates normalize, dedupe, sort, and display as M/D/YY lines', () => {
  const dates = tracker.parseStartDateList('Fall note 2026-08-17T00:00:00; 8/10/26, 08/10/2026\n9/1/2026');
  assert.deepEqual(dates, ['2026-08-10', '2026-08-17', '2026-09-01']);
  assert.equal(tracker.formatStartDateDisplay(dates), '8/10/26\n8/17/26\n9/1/26');
});

test('low enrollment snapshot columns use M-D-YY enrollment labels', () => {
  assert.equal(tracker.formatSnapshotColumnLabel('2026-08-07'), '8-7-26 Enrollment');
});

test('low enrollment baseline refresh preserves manual comments and dated snapshots', () => {
  const existing = tracker.parseWorkbookTable([
    ['Course(s)', 'CRN(s)', 'Title', 'Current Enrollment', 'Max Enrollment', 'Wait Count', 'Inst. Method', 'Sched Type', 'Applied Rule', 'Threshold', 'Start Date', 'Division', 'Campus', 'Faculty', 'Justification', 'Comments to VPs Office'],
    ['COMM C1000', '10003 / 10004', 'Old Public Speaking', '18', '30', '0', 'IP', 'LEC', 'Below 70%', '21', '8/10/2026', 'LANG', 'COS', 'Smith', 'Other', 'VP note'],
    ['MATH 021', '20001', 'Support Algebra', '8', '25', '0', 'IP', 'LEC', 'Below 70%', '18', '8/10/2026', 'MATH', 'TCC', 'Jones', '', '']
  ], { filename: '202710 FA26 Low Enrolled Watchlist_8-4-26.xlsx' });
  const afterSnapshot = tracker.applyEnrollmentSnapshot(existing, [
    { CRN: '10003', ACTUAL_ENROLL: '12' },
    { CRN: '10004', ACTUAL_ENROLL: '13' }
  ], { snapshotDate: '2026-08-11', sourceFilename: 'update.csv' }).workspace;
  const incoming = tracker.parseWorkbookTable([
    ['Course(s)', 'CRN(s)', 'Title', 'Current Enrollment', 'Max Enrollment', 'Wait Count', 'Inst. Method', 'Sched Type', 'Applied Rule', 'Threshold', 'Start Date', 'Division', 'Campus', 'Faculty'],
    ['COMM C1000', '10004, 10003', 'New Public Speaking', '19', '35', '2', 'HYB', 'LEC', 'Below 75%', '26', '8/17/2026', 'COMM', 'HAC', 'Smith'],
    ['ENGL C1000', '30001', 'Writing', '12', '30', '0', 'IP', 'LEC', 'Below 70%', '21', '8/17/2026', 'ENGL', 'COS', 'Rivera']
  ], { filename: '202710 FA26 Low Enrolled Watchlist_8-5-26.xlsx', throwOnInvalid: false });
  const result = tracker.refreshBaselineWorkspace(afterSnapshot, incoming);
  assert.equal(result.summary.matchedRows, 1);
  assert.equal(result.summary.newRows, 1);
  assert.equal(result.summary.missingRows, 1);
  assert.equal(result.workspace.rows[0].title, 'New Public Speaking');
  assert.equal(result.workspace.rows[0].justification, 'Other');
  assert.equal(result.workspace.rows[0].vpComments, 'VP note');
  assert.equal(result.workspace.rows[0].latestEnrollment, 25);
  assert.equal(result.workspace.rows[0].snapshotValues['2026-08-11'], 25);
  assert.equal(result.workspace.rows[1].missingFromLatestWorkbook, true);
});

test('low enrollment module source includes multi-select filters, sort controls, and explicit result modals', () => {
  const source = fs.readFileSync(path.join(__dirname, '..', 'js', 'low-enrollment-tracker.js'), 'utf8');
  assert.match(source, /data-filter-menu/);
  assert.match(source, /data-filter-apply/);
  assert.match(source, /data-sort-key/);
  assert.match(source, /Enrollment Update Saved with Warnings/);
  assert.match(source, /Replace Entire Workspace/);
  assert.doesNotMatch(source, /new Date\(\)\.toISOString\(\)\.slice\(0, 10\)/);
});

test('low enrollment worksheet freezes only requested regions and keeps timeline navigation scoped', () => {
  const source = fs.readFileSync(path.join(__dirname, '..', 'js', 'low-enrollment-tracker.js'), 'utf8');
  assert.match(source, /sticky-left sticky-course/);
  assert.match(source, /sticky-left sticky-crn/);
  assert.match(source, /sticky-left sticky-title/);
  assert.match(source, /sticky-right sticky-status/);
  assert.match(source, /sticky-right sticky-justification/);
  assert.match(source, /sticky-right sticky-comments/);
  assert.doesNotMatch(source, /sticky-right sticky-latest/);
  assert.doesNotMatch(source, /sticky-right sticky-highest/);
  assert.doesNotMatch(source, /sticky-right sticky-threshold/);
  assert.match(source, /data-timeline-column="true"/);
  assert.match(source, /const emptyColspan = 18 \+ timelineColumns\.length/);
  assert.match(source, /calculateTimelineNavigationScroll/);
  assert.match(source, /measuredFrozenTimelineWidths/);
  assert.doesNotMatch(source, /scrollLeft \+ 600|scrollLeft - 600|offsetLeft - 120/);
  assert.doesNotMatch(source, /exportLowEnrollmentCsv|Export CSV|exportFilteredCsv/);
});

test('low enrollment timeline navigation accounts for frozen left and right panes', () => {
  const limits = tracker.calculateTimelineScrollLimits({
    firstColumnLeft: 280,
    lastColumnRight: 1436,
    viewportWidth: 1000,
    scrollWidth: 1900,
    frozenLeftWidth: 280,
    frozenRightWidth: 360,
    padding: 8
  });
  assert.deepEqual(limits, { minScrollLeft: 0, maxScrollLeft: 804 });

  const latestScroll = tracker.calculateTimelineNavigationScroll({
    currentScrollLeft: 0,
    viewportWidth: 1000,
    scrollWidth: 1900,
    frozenLeftWidth: 280,
    frozenRightWidth: 360,
    targetLeft: 1350,
    targetRight: 1436,
    minScrollLeft: limits.minScrollLeft,
    maxScrollLeft: limits.maxScrollLeft,
    padding: 8
  });
  assert.equal(latestScroll, 804);
  assert.ok(1350 >= latestScroll + 280 + 8);
  assert.ok(1436 <= latestScroll + 1000 - 360 - 8);

  const updatedScroll = tracker.calculateTimelineNavigationScroll({
    currentScrollLeft: 804,
    viewportWidth: 1000,
    scrollWidth: 1900,
    frozenLeftWidth: 280,
    frozenRightWidth: 360,
    targetLeft: 365,
    targetRight: 451,
    minScrollLeft: limits.minScrollLeft,
    maxScrollLeft: limits.maxScrollLeft,
    padding: 8
  });
  assert.equal(updatedScroll, 77);
  assert.ok(365 >= updatedScroll + 280 + 8);
  assert.ok(451 <= updatedScroll + 1000 - 360 - 8);
});

test('low enrollment missing snapshot cells render both missing class and visible text', () => {
  const source = fs.readFileSync(path.join(__dirname, '..', 'js', 'low-enrollment-tracker.js'), 'utf8');
  assert.match(source, /snapshot-\$\{escapeHtml\(matchStatus\)\}/);
  assert.match(source, /<span class="muted">Missing<\/span>/);
});

test('low enrollment report is registered as an Enrollment Management report', () => {
  const { REPORTS, REPORT_ACCESS, REPORT_LABEL, REPORT_WORKFLOW_GROUPS, REPORT_DESCRIPTIONS } = reports;
  assert.equal(REPORTS.lowEnrollmentTracking, 'low-enrollment-tracking');
  assert.equal(REPORT_ACCESS[REPORTS.lowEnrollmentTracking], 'development');
  assert.equal(REPORT_LABEL[REPORTS.lowEnrollmentTracking], 'Low Enrollment Tracking');
  assert.ok(REPORT_WORKFLOW_GROUPS.find(group => group.key === 'enrollment-management').reports.includes(REPORTS.lowEnrollmentTracking));
  assert.match(REPORT_DESCRIPTIONS[REPORTS.lowEnrollmentTracking], /low-enrolled sections/i);
});

test('low enrollment module and index expose persistent backend wiring', () => {
  const root = path.join(__dirname, '..');
  const index = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
  const source = fs.readFileSync(path.join(root, 'js', 'low-enrollment-tracker.js'), 'utf8');

  assert.ok(index.indexOf('js/low-enrollment-tracker.js') < index.indexOf('js/enrollment-analytics.js'));
  assert.match(source, /\/api\/low-enrollment-tracking/);
  assert.match(source, /method: 'PATCH'/);
  assert.match(source, /Authorization: `Bearer/);
});
