const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');

const tracker = require('../js/low-enrollment-tracker.js');
const reports = require('../js/config/reports.js');

test('low enrollment tracker parses the workbook shape and hidden reasons fallback', () => {
  const table = [
    ['Report generated by Argos'],
    ['Course(s)', 'CRN(s)', 'Title', 'Cross List', 'CRN Count', 'Current Enrollment', 'Max Enrollment', 'Wait Count', 'Inst. \nMethod', 'Sched \nType', 'Applied Rule', 'Threshold', 'Start Date', 'Division', 'Campus', 'Faculty', 'Justification', 'Comments to VPs Office'],
    ['COMM C1000', '10003, 10004', 'Public Speaking', 'XL1', 2, 18, 30, 0, 'IP', 'LEC', 'Below 70%', 21, '8/10/2026', 'LANGUAGE', 'COS', 'Smith, A', 'Single section Offering in Visalia', 'keep watching'],
    ['MATH 021', '20001', 'Support Algebra', '', 1, 8, 25, 2, 'IP', 'LEC', 'Below 70%', 18, '8/10/2026', 'MATH', 'TCC', 'Jones, B', '', '']
  ];

  const workspace = tracker.parseWorkbookTable(table, { filename: '202710 FA26 Low Enrolled Watchlist_8-4-26.xlsx' });
  assert.equal(workspace.termCode, '202710');
  assert.equal(workspace.displayTerm, 'FALL 2026');
  assert.equal(workspace.initialSnapshotDate, '2026-08-04');
  assert.equal(workspace.rows.length, 2);
  assert.deepEqual(workspace.rows[0].crns, ['10003', '10004']);
  assert.equal(workspace.rows[0].initialEnrollment, 18);
  assert.equal(workspace.rows[0].threshold, 21);
  assert.equal(workspace.rows[0].status, 'Below Threshold');
  assert.ok(workspace.reasons.includes('Dual Enrollment'));
  assert.equal(tracker.DEFAULT_JUSTIFICATIONS.length, 10);
  assert.ok(workspace.importSummary.rowsImported === 2);

  const reasons = tracker.parseReasonsTable([['Reason'], ['Custom reason'], ['Custom reason']]);
  assert.deepEqual(reasons, ['Custom reason']);
});

test('low enrollment update sums cross-listed member CRNs and reports full/partial/missing matches', () => {
  const workspace = tracker.parseWorkbookTable([
    ['Course(s)', 'CRN(s)', 'Title', 'Current Enrollment', 'Max Enrollment', 'Threshold'],
    ['COMM C1000', '10003 / 10004', 'Public Speaking', 18, 30, 21],
    ['ENGL C1000', '30001 / 30002', 'Writing', 10, 30, 21],
    ['MATH 021', '40001', 'Support Algebra', 5, 30, 21]
  ], { filename: '202710 FA26 Low Enrolled Watchlist_8-4-26.xlsx' });

  const csvRows = [
    { CRN: '10003', ACTUAL_ENROLL: '12', 'SUBJECT/COURSE': 'COMM C1000' },
    { CRN: '10003', ACTUAL_ENROLL: '12', 'SUBJECT/COURSE': 'COMM C1000' },
    { CRN: '10004', ACTUAL_ENROLL: '13', 'SUBJECT/COURSE': 'COMM C1000' },
    { CRN: '30001', ACTUAL_ENROLL: '9', 'SUBJECT/COURSE': 'ENGL C1000' }
  ];
  const parsed = tracker.parseEnrollmentCsvRows(csvRows);
  assert.equal(parsed.size, 3);
  assert.equal(parsed.get('10003').enrollment, 12);

  const result = tracker.applyEnrollmentSnapshot(workspace, parsed, { snapshotDate: '2026-08-11', sourceFilename: 'section-seating.csv' });
  assert.equal(result.fullyMatchedRows, 1);
  assert.equal(result.partiallyMatchedRows, 1);
  assert.equal(result.completelyMissingRows, 1);
  assert.equal(result.individualCrnsMatched, 3);
  assert.equal(result.individualCrnsMissing, 2);
  assert.equal(result.newlyMet, 1);
  assert.equal(result.workspace.rows[0].latestEnrollment, 25);
  assert.equal(result.workspace.rows[0].highestEnrollment, 25);
  assert.equal(result.workspace.rows[0].status, 'Threshold Met');
  assert.equal(result.workspace.rows[1].latestEnrollment, 9);
  assert.equal(result.workspace.rows[1].snapshotMatchStatus['2026-08-11'], 'partial');
  assert.deepEqual(result.workspace.rows[1].snapshotMissingCrns['2026-08-11'], ['30002']);
  assert.equal(result.workspace.rows[2].latestEnrollment, null);
  assert.equal(result.workspace.rows[2].status, 'Presumed Cancelled');
  assert.deepEqual(result.snapshot.values[result.workspace.rows[0].id].matchedCrns, ['10003', '10004']);
});

test('low enrollment update treats disappeared CRNs as presumed cancelled and preserves safe threshold-met rows', () => {
  const workspace = tracker.parseWorkbookTable([
    ['Course(s)', 'CRN(s)', 'Title', 'Current Enrollment', 'Max Enrollment', 'Threshold'],
    ['COMM C1000', '10003', 'Public Speaking', 18, 30, 21],
    ['ENGL C1000', '30001', 'Writing', 10, 30, 21],
    ['MATH 021', '40001', 'Support Algebra', 5, 30, 18]
  ], { filename: '202710 FA26 Low Enrolled Watchlist_8-4-26.xlsx' });

  const firstUpdate = tracker.applyEnrollmentSnapshot(workspace, [
    { CRN: '10003', ACTUAL_ENROLL: '22' },
    { CRN: '30001', ACTUAL_ENROLL: '12' },
    { CRN: '40001', ACTUAL_ENROLL: '8' }
  ], { snapshotDate: '2026-08-11', sourceFilename: 'section-seating-8-11.csv' }).workspace;
  const secondUpdate = tracker.applyEnrollmentSnapshot(firstUpdate, [
    { CRN: '30001', ACTUAL_ENROLL: '13' }
  ], { snapshotDate: '2026-08-18', sourceFilename: 'section-seating-8-18.csv' }).workspace;
  const [safeRow, activeRow, cancelledRow] = secondUpdate.rows;

  assert.equal(tracker.statusForRow(safeRow), 'Threshold Met');
  assert.equal(safeRow.presumedCancelled, true);
  assert.equal(tracker.removedReason(safeRow), 'Threshold Met; Missing from Latest Enrollment Upload - Presumed Cancelled: 8/18/26');
  assert.equal(tracker.statusForRow(activeRow), 'Below Threshold');
  assert.equal(activeRow.presumedCancelled, false);
  assert.equal(tracker.statusForRow(cancelledRow), 'Presumed Cancelled');
  assert.equal(cancelledRow.presumedCancelledSnapshotDate, '2026-08-18');
  assert.equal(tracker.removedFromActiveWatchlist(cancelledRow), true);
  assert.equal(tracker.removedReason(cancelledRow), 'Missing from Latest Enrollment Upload - Presumed Cancelled: 8/18/26');

  const removed = tracker.removedOrExcludedExportRows(secondUpdate);
  const exportModel = tracker.buildExcelExportModel(secondUpdate, removed);
  const headers = exportModel.columns.map(column => column.header);
  const exportedByCourse = new Map(exportModel.rows.map(values => {
    const row = Object.fromEntries(headers.map((header, index) => [header, values[index]]));
    return [row.Course, row];
  }));
  assert.equal(removed.length, 2);
  assert.equal(exportedByCourse.get('COMM C1000').Status, 'Threshold Met');
  assert.equal(exportedByCourse.get('MATH 021').Status, 'Presumed Cancelled');
  assert.match(exportedByCourse.get('MATH 021')['Removed / Met Minimum Reason'], /Presumed Cancelled/);
});

test('low enrollment snapshot deletion removes dated column and recalculates row status', () => {
  const workspace = tracker.parseWorkbookTable([
    ['Course(s)', 'CRN(s)', 'Title', 'Current Enrollment', 'Max Enrollment', 'Threshold'],
    ['COMM C1000', '10003', 'Public Speaking', 18, 30, 21],
    ['ENGL C1000', '30001', 'Writing', 10, 30, 21]
  ], { filename: '202710 FA26 Low Enrolled Watchlist_8-4-26.xlsx' });
  const firstUpdate = tracker.applyEnrollmentSnapshot(workspace, [
    { CRN: '10003', ACTUAL_ENROLL: '20' },
    { CRN: '30001', ACTUAL_ENROLL: '12' }
  ], { snapshotDate: '2026-08-11', sourceFilename: 'good-date.csv' }).workspace;
  const badDateUpdate = tracker.applyEnrollmentSnapshot(firstUpdate, [
    { CRN: '10003', ACTUAL_ENROLL: '25' }
  ], { snapshotDate: '2026-08-99', sourceFilename: 'wrong-date.csv' }).workspace;

  assert.equal(badDateUpdate.rows[0].status, 'Threshold Met');
  assert.equal(badDateUpdate.rows[0].highestEnrollment, 25);
  assert.equal(badDateUpdate.rows[1].status, 'Presumed Cancelled');
  assert.equal(badDateUpdate.snapshots.some(snapshot => snapshot.snapshotDate === '2026-08-99'), true);

  const deleted = tracker.deleteEnrollmentSnapshot(badDateUpdate, '2026-08-99').workspace;
  assert.equal(deleted.snapshots.some(snapshot => snapshot.snapshotDate === '2026-08-99'), false);
  assert.equal(Object.prototype.hasOwnProperty.call(deleted.rows[0].snapshotValues, '2026-08-99'), false);
  assert.equal(deleted.rows[0].latestEnrollment, 20);
  assert.equal(deleted.rows[0].highestEnrollment, 20);
  assert.equal(deleted.rows[0].status, 'Below Threshold');
  assert.equal(deleted.rows[1].latestEnrollment, 12);
  assert.equal(deleted.rows[1].presumedCancelled, false);
  assert.equal(deleted.rows[1].status, 'Below Threshold');
  assert.equal(deleted.uploadHistory.at(-1).type, 'snapshot-delete');
});

test('low enrollment workbook validation rejects missing threshold values', () => {
  assert.throws(() => tracker.parseWorkbookTable([
    ['Course(s)', 'CRN(s)', 'Title', 'Current Enrollment', 'Max Enrollment'],
    ['COMM C1000', '10003', 'Public Speaking', 18, 30]
  ], { filename: '202710 FA26 Low Enrolled Watchlist_8-4-26.xlsx' }), /threshold/i);

  const workspace = tracker.parseWorkbookTable([
    ['Course(s)', 'CRN(s)', 'Title', 'Current Enrollment', 'Max Enrollment'],
    ['COMM C1000', '10003', 'Public Speaking', 18, 30]
  ], { filename: '202710 FA26 Low Enrolled Watchlist_8-4-26.xlsx', throwOnInvalid: false });
  assert.equal(workspace.importErrors.length, 2);
  assert.match(workspace.importErrors.join(' '), /threshold/i);
});

test('low enrollment snapshot date detects source content before filename fallback', () => {
  assert.equal(tracker.detectSnapshotDateFromRows([{ SNAPSHOT_DATE: '8/12/2026' }]), '2026-08-12');
  assert.equal(tracker.extractSnapshotDateFromFilename('202710 FA26 Low Enrolled Watchlist_8-4-26.xlsx'), '2026-08-04');
});

test('low enrollment start dates normalize, dedupe, sort, and display as M/D/YY lines', () => {
  const dates = tracker.parseStartDateList('Fall note 2026-08-17T00:00:00; 8/10/26, 08/10/2026\n9/1/2026');
  assert.deepEqual(dates, ['2026-08-10', '2026-08-17', '2026-09-01']);
  assert.equal(tracker.formatStartDateDisplay(dates), '8/10/26\n8/17/26\n9/1/26');
});

test('low enrollment snapshot columns use M-D-YY enrollment labels', () => {
  assert.equal(tracker.formatSnapshotColumnLabel('2026-08-07'), '8-7-26 Enrollment');
});

test('low enrollment baseline refresh preserves manual comments and dated snapshots', () => {
  const existing = tracker.parseWorkbookTable([
    ['Course(s)', 'CRN(s)', 'Title', 'Current Enrollment', 'Max Enrollment', 'Wait Count', 'Inst. Method', 'Sched Type', 'Applied Rule', 'Threshold', 'Start Date', 'Division', 'Campus', 'Faculty', 'Justification', 'Comments to VPs Office'],
    ['COMM C1000', '10003 / 10004', 'Old Public Speaking', '18', '30', '0', 'IP', 'LEC', 'Below 70%', '21', '8/10/2026', 'LANG', 'COS', 'Smith', 'Other', 'VP note'],
    ['MATH 021', '20001', 'Support Algebra', '8', '25', '0', 'IP', 'LEC', 'Below 70%', '18', '8/10/2026', 'MATH', 'TCC', 'Jones', '', '']
  ], { filename: '202710 FA26 Low Enrolled Watchlist_8-4-26.xlsx' });
  const afterSnapshot = tracker.applyEnrollmentSnapshot(existing, [
    { CRN: '10003', ACTUAL_ENROLL: '12' },
    { CRN: '10004', ACTUAL_ENROLL: '13' }
  ], { snapshotDate: '2026-08-11', sourceFilename: 'update.csv' }).workspace;
  const incoming = tracker.parseWorkbookTable([
    ['Course(s)', 'CRN(s)', 'Title', 'Current Enrollment', 'Max Enrollment', 'Wait Count', 'Inst. Method', 'Sched Type', 'Applied Rule', 'Threshold', 'Start Date', 'Division', 'Campus', 'Faculty'],
    ['COMM C1000', '10004, 10003', 'New Public Speaking', '19', '35', '2', 'HYB', 'LEC', 'Below 75%', '26', '8/17/2026', 'COMM', 'HAC', 'Smith'],
    ['ENGL C1000', '30001', 'Writing', '12', '30', '0', 'IP', 'LEC', 'Below 70%', '21', '8/17/2026', 'ENGL', 'COS', 'Rivera']
  ], { filename: '202710 FA26 Low Enrolled Watchlist_8-5-26.xlsx', throwOnInvalid: false });
  const result = tracker.refreshBaselineWorkspace(afterSnapshot, incoming);
  assert.equal(result.summary.matchedRows, 1);
  assert.equal(result.summary.newRows, 1);
  assert.equal(result.summary.missingRows, 1);
  assert.equal(result.workspace.rows[0].title, 'New Public Speaking');
  assert.equal(result.workspace.rows[0].justification, 'Other');
  assert.equal(result.workspace.rows[0].vpComments, 'VP note');
  assert.equal(result.workspace.rows[0].latestEnrollment, 25);
  assert.equal(result.workspace.rows[0].snapshotValues['2026-08-11'], 25);
  assert.equal(result.workspace.rows[1].missingFromLatestWorkbook, true);
});

test('low enrollment module source includes multi-select filters, sort controls, and explicit result modals', () => {
  const source = fs.readFileSync(path.join(__dirname, '..', 'js', 'low-enrollment-tracker.js'), 'utf8');
  assert.match(source, /data-filter-menu/);
  assert.match(source, /data-filter-apply/);
  assert.match(source, /data-sort-key/);
  assert.match(source, /Enrollment Update Saved with Warnings/);
  assert.match(source, /Replace Entire Workspace/);
  assert.doesNotMatch(source, /new Date\(\)\.toISOString\(\)\.slice\(0, 10\)/);
});

test('low enrollment worksheet freezes only requested regions and keeps timeline navigation scoped', () => {
  const source = fs.readFileSync(path.join(__dirname, '..', 'js', 'low-enrollment-tracker.js'), 'utf8');
  assert.match(source, /sticky-left sticky-course/);
  assert.match(source, /sticky-left sticky-crn/);
  assert.match(source, /sticky-left sticky-title/);
  assert.match(source, /sticky-right sticky-status/);
  assert.match(source, /sticky-right sticky-justification/);
  assert.match(source, /sticky-right sticky-comments/);
  assert.doesNotMatch(source, /sticky-right sticky-latest/);
  assert.doesNotMatch(source, /sticky-right sticky-highest/);
  assert.doesNotMatch(source, /sticky-right sticky-threshold/);
  assert.match(source, /data-timeline-column="true"/);
  assert.match(source, /const emptyColspan = 17 \+ timelineColumns\.length/);
  assert.match(source, /calculateTimelineNavigationScroll/);
  assert.match(source, /measuredFrozenTimelineWidths/);
  assert.doesNotMatch(source, /scrollLeft \+ 600|scrollLeft - 600|offsetLeft - 120/);
  assert.doesNotMatch(source, /exportLowEnrollmentCsv|Export CSV|exportFilteredCsv/);
  assert.match(source, /Export Current View to Excel/);
});

test('low enrollment Excel export preserves visible data and justification dropdown metadata', () => {
  const workspace = tracker.parseWorkbookTable([
    ['Course(s)', 'CRN(s)', 'Title', 'Current Enrollment', 'Max Enrollment', 'Wait Count', 'Inst. Method', 'Sched Type', 'Applied Rule', 'Threshold', 'Start Date', 'Division', 'Campus', 'Faculty', 'Justification', 'Comments to VPs Office'],
    ['ENGL C1000', '12345', 'Composition', 12, 30, 1, 'IP', 'LEC', 'Rule 1', 15, '8/17/26', 'Arts', 'COS', 'Ada Lovelace', 'Other', 'Review']
  ], { filename: '202710 FA26 Low Enrolled Watchlist_8-4-26.xlsx', reasons: ['Other', 'Required course'] });
  const model = tracker.buildExcelExportModel(workspace, workspace.rows);
  assert.equal(model.rows.length, 1);
  assert.equal(model.columns[model.justificationColumnIndex - 1].header, 'Justification');
  assert.equal(model.rows[0][model.justificationColumnIndex - 1], 'Other');
  assert.deepEqual(model.reasons, ['Other', 'Required course']);
  assert.ok(model.columns.some(column => column.header === '1st Day Enrollment'));
  assert.equal(model.columns.some(column => column.header === 'Wait Count'), false);

  const source = fs.readFileSync(path.join(__dirname, '..', 'js', 'low-enrollment-tracker.js'), 'utf8');
  assert.match(source, /state = 'veryHidden'/);
  assert.match(source, /formulae: \['JustificationOptions'\]/);
  assert.match(source, /dataValidation/);
  assert.match(source, /addWorksheet\('Removed Sections'/);
  assert.match(source, /topLeftCell: 'D2'/);
  assert.match(source, /activeCell: 'D2'/);
  assert.ok(model.columns.find(column => column.key === '_timberRowId').hidden);
  assert.ok(model.columns.find(column => column.key === '_timberTermCode').hidden);
});

test('edited tracker import changes only manual fields, accepts clearing, and rejects custom justifications', () => {
  const workspace = tracker.parseWorkbookTable([
    ['Course(s)', 'CRN(s)', 'Title', 'Current Enrollment', 'Max Enrollment', 'Threshold', 'Justification', 'Comments to VPs Office'],
    ['COMM C1000', '10003', 'Speaking', 10, 30, 21, 'Other', 'Existing note']
  ], { filename: '202710 FA26 Low Enrolled Watchlist_8-4-26.xlsx' });
  const row = workspace.rows[0];
  const priorXlsx = global.XLSX;
  global.XLSX = { utils: { sheet_to_json: sheet => sheet } };
  try {
    const headers = ['Course', 'Justification', 'Comments to VPs Office', 'Timber Row ID', 'Timber Term Code', 'Timber Import Schema', 'Timber Original Justification', 'Timber Original VP Comments'];
    const workbook = { SheetNames: ['Low Enrollment'], Sheets: { 'Low Enrollment': [
      headers,
      ['COMM C1000', '', '', row.id, '202710', 'TIMBER_LOW_ENROLLMENT_MANUAL_V1', 'Other', 'Existing note']
    ] } };
    const preview = tracker.parseManualUpdateWorkbook(workbook, workspace);
    assert.equal(preview.valid, true);
    assert.deepEqual(preview.updates, [{ rowId: row.id, justification: '', vpComments: '', expectedJustification: 'Other', expectedVpComments: 'Existing note' }]);
    assert.equal(preview.summary.clearedJustifications, 1);
    assert.equal(preview.summary.clearedVpComments, 1);

    workbook.Sheets['Low Enrollment'][1][1] = 'Typed custom reason';
    const invalid = tracker.parseManualUpdateWorkbook(workbook, workspace);
    assert.equal(invalid.valid, false);
    assert.match(invalid.errors.join(' '), /dropdown list/i);
  } finally {
    global.XLSX = priorXlsx;
  }
});

test('baseline refresh preserves term-specific exclusion metadata', () => {
  const existing = tracker.parseWorkbookTable([
    ['Course(s)', 'CRN(s)', 'Title', 'Current Enrollment', 'Max Enrollment', 'Threshold'],
    ['LA 425', '10003', 'Open Lab', 2, 30, 21]
  ], { filename: '202710 watchlist_8-4-26.xlsx' });
  existing.rows[0].exclusion = { excluded: true, reason: 'Open lab', note: 'Accepted exception' };
  const incoming = tracker.parseWorkbookTable([
    ['Course(s)', 'CRN(s)', 'Title', 'Current Enrollment', 'Max Enrollment', 'Threshold'],
    ['LA 425', '10003', 'Open Lab', 3, 30, 21]
  ], { filename: '202710 watchlist_8-5-26.xlsx' });
  const refreshed = tracker.refreshBaselineWorkspace(existing, incoming).workspace;
  assert.equal(refreshed.rows[0].exclusion.excluded, true);
  assert.equal(refreshed.rows[0].exclusion.reason, 'Open lab');
});

test('low enrollment timeline navigation accounts for frozen left and right panes', () => {
  const limits = tracker.calculateTimelineScrollLimits({
    firstColumnLeft: 280,
    lastColumnRight: 1436,
    viewportWidth: 1000,
    scrollWidth: 1900,
    frozenLeftWidth: 280,
    frozenRightWidth: 360,
    padding: 8
  });
  assert.deepEqual(limits, { minScrollLeft: 0, maxScrollLeft: 804 });

  const latestScroll = tracker.calculateTimelineNavigationScroll({
    currentScrollLeft: 0,
    viewportWidth: 1000,
    scrollWidth: 1900,
    frozenLeftWidth: 280,
    frozenRightWidth: 360,
    targetLeft: 1350,
    targetRight: 1436,
    minScrollLeft: limits.minScrollLeft,
    maxScrollLeft: limits.maxScrollLeft,
    padding: 8
  });
  assert.equal(latestScroll, 804);
  assert.ok(1350 >= latestScroll + 280 + 8);
  assert.ok(1436 <= latestScroll + 1000 - 360 - 8);

  const updatedScroll = tracker.calculateTimelineNavigationScroll({
    currentScrollLeft: 804,
    viewportWidth: 1000,
    scrollWidth: 1900,
    frozenLeftWidth: 280,
    frozenRightWidth: 360,
    targetLeft: 365,
    targetRight: 451,
    minScrollLeft: limits.minScrollLeft,
    maxScrollLeft: limits.maxScrollLeft,
    padding: 8
  });
  assert.equal(updatedScroll, 77);
  assert.ok(365 >= updatedScroll + 280 + 8);
  assert.ok(451 <= updatedScroll + 1000 - 360 - 8);
});

test('low enrollment missing snapshot cells render both missing class and visible text', () => {
  const source = fs.readFileSync(path.join(__dirname, '..', 'js', 'low-enrollment-tracker.js'), 'utf8');
  assert.match(source, /snapshot-\$\{escapeHtml\(matchStatus\)\}/);
  assert.match(source, /<span class="muted">Missing<\/span>/);
});

test('low enrollment export rows identify threshold-met and excluded sections for the second workbook tab', () => {
  const workspace = tracker.parseWorkbookTable([
    ['Course(s)', 'CRN(s)', 'Title', 'Current Enrollment', 'Max Enrollment', 'Threshold'],
    ['COMM C1000', '10003', 'Public Speaking', 18, 30, 21],
    ['ENGL C1000', '30001', 'Writing', 10, 30, 21],
    ['LA 425', '40001', 'Open Lab', 2, 30, 21]
  ], { filename: '202710 FA26 Low Enrolled Watchlist_8-4-26.xlsx' });
  const updated = tracker.applyEnrollmentSnapshot(workspace, [
    { CRN: '10003', ACTUAL_ENROLL: '22' },
    { CRN: '30001', ACTUAL_ENROLL: '12' },
    { CRN: '40001', ACTUAL_ENROLL: '3' }
  ], { snapshotDate: '2026-08-11', sourceFilename: 'update.csv' }).workspace;
  updated.rows[2].exclusion = { excluded: true, reason: 'Open lab', note: 'Accepted exception' };
  const removed = tracker.removedOrExcludedExportRows(updated);
  const exportModel = tracker.buildExcelExportModel(updated, removed);
  const headers = exportModel.columns.map(column => column.header);
  const removedRow = Object.fromEntries(headers.map((header, index) => [header, exportModel.rows[0][index]]));
  const excludedRow = Object.fromEntries(headers.map((header, index) => [header, exportModel.rows[1][index]]));

  assert.equal(removed.length, 2);
  assert.equal(removedRow.Status, 'Threshold Met');
  assert.equal(removedRow['1st Day Enrollment'], 18);
  assert.equal(removedRow['Removed / Met Minimum Reason'], 'Threshold Met');
  assert.equal(removedRow['8-11-26 Enrollment'], 22);
  assert.equal(excludedRow.Course, 'LA 425');
  assert.equal(excludedRow.Status, 'Below Threshold');
  assert.equal(excludedRow['Removed / Met Minimum Reason'], 'Excluded from Tracking: Open lab: Accepted exception');
  assert.equal(Object.prototype.hasOwnProperty.call(removedRow, 'Wait Count'), false);
});

test('low enrollment report is registered as a Dean report', () => {
  const { REPORTS, REPORT_ACCESS, REPORT_LABEL, REPORT_WORKFLOW_GROUPS, REPORT_DESCRIPTIONS } = reports;
  assert.equal(REPORTS.lowEnrollmentTracking, 'low-enrollment-tracking');
  assert.equal(REPORT_ACCESS[REPORTS.lowEnrollmentTracking], 'dean');
  assert.equal(REPORT_LABEL[REPORTS.lowEnrollmentTracking], 'Low Enrollment Tracking');
  assert.ok(REPORT_WORKFLOW_GROUPS.find(group => group.key === 'dean').reports.includes(REPORTS.lowEnrollmentTracking));
  assert.equal(REPORT_WORKFLOW_GROUPS.find(group => group.key === 'enrollment-management').reports.includes(REPORTS.lowEnrollmentTracking), false);
  assert.match(REPORT_DESCRIPTIONS[REPORTS.lowEnrollmentTracking], /low-enrolled sections/i);
});

test('low enrollment module and index expose persistent backend wiring', () => {
  const root = path.join(__dirname, '..');
  const index = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
  const source = fs.readFileSync(path.join(root, 'js', 'low-enrollment-tracker.js'), 'utf8');

  assert.ok(index.indexOf('js/low-enrollment-tracker.js') < index.indexOf('js/enrollment-analytics.js'));
  assert.match(source, /\/api\/low-enrollment-tracking/);
  assert.match(source, /method: 'PATCH'/);
  assert.match(source, /Authorization: `Bearer/);
});
