const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');
const vm = require('node:vm');

const ROOT = path.join(__dirname, '..');

function read(relativePath) {
  return fs.readFileSync(path.join(ROOT, relativePath), 'utf8');
}

function runBrowserModules(files) {
  const context = {
    window: {},
    console
  };
  context.window.window = context.window;
  vm.createContext(context);
  files.forEach(file => {
    vm.runInContext(read(file), context, { filename: file });
  });
  return context.window;
}

function section(overrides = {}) {
  return {
    term: 'FALL 2026',
    crn: overrides.crn || '10001',
    subject: overrides.subject || 'ENGL',
    course: overrides.course || 'C1000',
    title: overrides.title || 'College Reading and Writing',
    section: overrides.section || '001',
    units: overrides.units ?? 3,
    campus: overrides.campus || 'COS',
    division: overrides.division || 'Language Arts',
    discipline: overrides.discipline || overrides.subject || 'ENGL',
    modality: overrides.modality || 'In-Person',
    days: overrides.days || ['MO'],
    start: overrides.start || '09:00',
    end: overrides.end || '10:00',
    cap: overrides.cap ?? 30,
    actual: overrides.actual ?? 24,
    census: overrides.census ?? 25,
    waitlist: overrides.waitlist ?? 0,
    SCHD_CODE_SSRMEET: overrides.component || 'LEC',
    ...overrides
  };
}

test('regression baseline: application shell and script contracts are present', () => {
  const html = read('index.html');

  [
    'term-tabs',
    'viewSelect',
    'availability-ui',
    'schedule-table',
    'heatmap-tool',
    'export-pdf-btn'
  ].forEach(id => assert.match(html, new RegExp(`id="${id}"`), `${id} should remain in the application shell`));

  assert.match(html, /js\/app\.js/);
  assert.match(html, /js\/enrollment-analytics\.js/);
  assert.ok(html.indexOf('js/app.js') < html.indexOf('js/enrollment-analytics.js'), 'app.js should load before enrollment-analytics.js');

  const analytics = read('js/enrollment-analytics.js');
  assert.match(analytics, /id="emReportSelect"/, 'emReportSelect is generated by enrollment-analytics.js');
  assert.match(analytics, /id="scheduleBuilderReport"/, 'scheduleBuilderReport is generated by enrollment-analytics.js');
  assert.match(analytics, /id="dashboardReport"/, 'dashboardReport is generated by enrollment-analytics.js');
});

test('regression baseline: report navigation registry keeps representative reports wired', () => {
  const analytics = read('js/enrollment-analytics.js');

  [
    'dashboard',
    'demand',
    'heatmap',
    'studentPresence',
    'instructorAvailability',
    'facultyHeatmap',
    'scheduleBuilder',
    'scheduleOptimizationLab',
    'workExperience'
  ].forEach(report => assert.match(analytics, new RegExp(`${report}:`), `${report} should remain in REPORTS`));

  assert.match(analytics, /REPORT_WORKFLOW_GROUPS/);
  assert.match(analytics, /REPORT_ACCESS/);
  assert.match(analytics, /setReportDisplay\(REPORTS\.scheduleBuilder, 'scheduleBuilderReport'\)/);
  assert.match(analytics, /setReportDisplay\(REPORTS\.dashboard, 'dashboardReport'\)/);
  assert.match(analytics, /window\.COSScheduleApp\?\.renderHeatmapAnalytics\?\.\(\)/);
});

test('regression baseline: backend schedule load and room availability rendering remain wired', () => {
  const app = read('js/app.js');

  assert.match(app, /async function loadScheduleFromBackend\(term/);
  assert.match(app, /\/api\/schedule\/\$\{encodeURIComponent\(term\)\}/);
  assert.match(app, /currentData = \(data \|\| \[\]\)\.map\(normalizeRow\)/);
  assert.match(app, /renderSchedule\(\)/);
  assert.match(app, /function handleAvailability\(/);
  assert.match(app, /document\.getElementById\('avail-check-btn'\)/);
  assert.match(app, /window\.COSScheduleApp = \{/);
});

test('regression baseline: Schedule Builder accepts course inputs and produces options', () => {
  const builder = require('../js/core/schedule-builder.js');
  const result = builder.buildScheduleOptions([
    section({ crn: '10001', subject: 'ENGL', course: 'C1000', start: '09:00', end: '10:00' }),
    section({ crn: '10002', subject: 'COMM', course: 'C1000', start: '10:30', end: '11:30' })
  ], [
    { course: 'ENGL C1000', required: true },
    { course: 'COMM C1000', required: true }
  ], { requireAllRequestedCourses: true });

  assert.equal(result.schedules.length, 1);
  assert.equal(result.schedules[0].sections.length, 2);
  assert.equal(result.schedules[0].complete, true);
});

test('regression baseline: one enrollment report calculation returns renderable summary data', () => {
  const window = runBrowserModules([
    'js/core/term-utils.js',
    'js/core/day-utils.js',
    'js/core/csv-normalizer.js',
    'js/core/formatters.js',
    'js/core/modality-normalizer.js',
    'js/core/physical-time.js',
    'js/core/section-model.js',
    'js/enrollment/metrics.js',
    'js/enrollment/filters.js',
    'js/enrollment/consolidation.js',
    'js/enrollment/dashboard.js'
  ]);

  const summary = window.COSEnrollmentDashboard.dashboardSummary([
    section({ crn: '10001', subject: 'ENGL', census: 25, cap: 30 }),
    section({ crn: '10002', subject: 'MATH', course: '010', census: 20, cap: 25 })
  ], [], []);

  assert.equal(summary.health.currentEnrollment, 45);
  assert.equal(summary.health.sectionsReviewed, 2);
  assert.ok(Array.isArray(summary.pace));
});

test('regression baseline: one export data path completes without uncaught errors', () => {
  const window = runBrowserModules([
    'js/core/term-utils.js',
    'js/core/day-utils.js',
    'js/core/csv-normalizer.js',
    'js/core/formatters.js',
    'js/core/modality-normalizer.js',
    'js/core/physical-time.js',
    'js/core/section-model.js',
    'js/enrollment/metrics.js',
    'js/enrollment/filters.js',
    'js/enrollment/consolidation.js',
    'js/enrollment/dashboard.js'
  ]);

  const summary = window.COSEnrollmentDashboard.dashboardSummary([section()], [], []);
  const rows = window.COSEnrollmentDashboard.dashboardSummaryExportRows(summary, {
    selectedTerm: 'FALL 2026',
    exportedAt: '2026-07-18T00:00:00.000Z'
  });

  assert.ok(rows.length > 0);
  assert.doesNotThrow(() => JSON.stringify(rows));
  assert.ok(rows.some(row => Object.values(row).includes('FALL 2026')));
});
